#!/usr/local/bin/python
import argparse
import yaml
import os
import sys

parser = argparse.ArgumentParser(
        description='Welcome to eukrhythmic! By default, all rules are run, unless you have ' + 
                    'not provided a spikefile/spiketable. Otherwise, please select "all" to run all rules, ' +  
                    '"setup" to run FastQC and Trimmommatic, "assembly" to assemble trimmed files, "merge" to run ' + 
                    'concatenation and clustering steps, "analysis" to run Pfam, EUKulele, and KEGG ' +
                    'annotation on output, or "analysis-spike" to do analysis with spike table counts.',
        usage='eukrhythmic [subroutine] --jobs <max number of jobs to deploy>')

parser.add_argument('subroutine', metavar="subroutine", nargs='?', type=str, default="all", 
                        choices = ["","all","setup","assembly","merge","analysis"], 
                        help='Choice of subroutine to run.')
parser.add_argument('--rerun-incomplete', action='store_true', default=False,
                    help='Whether to tell Snakemake to rerun incomplete jobs.')

parser.add_argument('-j', '--jobs', dest = "jobs", default = 30)
parser.add_argument('-s', '--system', dest = "system", choices = ["slurm", "pbs", "qsub", "sbatch"], 
                    default = "slurm",
                    help = "What HPC system you are running eukrhythmic on.")
parser.add_argument('-q', '--queue', dest = "queue", default = "",
                    help = "Which queue to submit to on the HPC. Not included if not specified")
parser.add_argument('-np', '--np', dest = "np", action = "store_true", default = False,
                    help = "Whether to just do a dry run.")
parser.add_argument('-u', '--unlock', dest = "unlock", action = "store_true", default = False)
parser.add_argument('-c', '--configfile', dest = "config", default = "config.yaml")

args = parser.parse_args()
print(args.config)
snakefile = "eukrhythmic"
with open(args.config) as f:
    config = yaml.load(f, Loader=yaml.FullLoader)
if ("spikefile" not in config) | ("spiketable" not in config):
    snakefile = "eukrhythmic"#-no-spike"

if args.subroutine == "setup":
    snakefile = "eukrhythmic-setup"
elif args.subroutine == "assembly":
    snakefile = "eukrhythmic-assembly"
elif args.subroutine == "merge":
    snakefile = "eukrhythmic-merge"
elif args.subroutine == "analysis":
    snakefile = "eukrhythmic-analysis"
elif args.subroutine == "analysis-spike":
    snakefile = "eukrhythmic-analysis-spike"

if args.np:
    os.system(" ".join(["snakemake","-s",str(snakefile),"--rerun-incomplete","-np","--cores",str(1)]))
    sys.exit(0)  
if args.unlock:
    os.system(" ".join(["snakemake","-s",str(snakefile),"--rerun-incomplete","--unlock","--cores",str(1)]))
    sys.exit(0) 

rerun_incomplete = ""
if args.rerun_incomplete:
    rerun_incomplete = "--rerun-incomplete"
if (args.system == "sbatch") | (args.system == "slurm"):
    os.system(" ".join(["sbatch",os.path.join("submit","snake-submit.sh"),snakefile,str(args.jobs),rerun_incomplete]))
elif (args.system == "qsub") | (args.system == "pbs"):
    submit_args = ["qsub",os.path.join("submit","snake-submit-pbs.sh"),snakefile,str(args.jobs),rerun_incomplete]
    if args.queue != "":
        submit_args.append("-q")
        submit_args.append(str(args.queue))
    os.system(" ".join(submit_args))
